import { Footer } from "@/components/footer";
import { Navbar } from "@/components/navbar";
import { WixClientContextProvider } from "@/context/wix-context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Navbar />
        <WixClientContextProvider>{children}</WixClientContextProvider>

        <Footer />
      </body>
    </html>
  );
}
